### ISSUE TITLE
Eternum API seem to have no CORS support

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/eternum-test#1]
It looks like the Eternum API, the one documented [here](https://www.eternum.io/api/docs/), **not** the IPFS gateway, doesn't support Cross-Origin Resource Sharing (CORS) requests.

Here I use this repo to try to issue a `GET` CORS requests to [`https://www.eternum.io/api/site`](https://www.eternum.io/api/site).

# Steps to reproduce

- Edit `main.js` with a valid Eternum key.
- Serve the files from the repo root. I do so with `python3 -m http.server`, on port 8000.
- Open the browser and visit the `index.html` page. In my case it's firefox and `http://localhost:8000`.

# Result

- The browser's console complains about CORS issues.
![Screenshot from 2020-03-21 15-27-39](https://user-images.githubusercontent.com/2564187/77227386-aec39900-6b88-11ea-8667-8caf1ff9a572.png)
- The browser's network page indicates that the `OPTIONS` requests returned status code 301. I don't really know if this is part of the problem or not. Adding `redirect: 'follow'` to `fetch`'s options doesn't change the response status code nor anything else I report here. Also, no `GET` request is issued after the `OPTIONS` requests as expected with CORS requests.
![Screenshot from 2020-03-21 15-27-39](https://user-images.githubusercontent.com/2564187/77227442-209be280-6b89-11ea-86cf-ca22cc9e3007.png)
- The response to the `OPTIONS` request is missing the "Access-Control-Allow-Origin”, “Access-Control-Allow-Methods”, and “Access-Control-Allow-Headers” headers that are AFAIK mandatory to support CORS requests.
![Screenshot from 2020-03-21 15-36-01](https://user-images.githubusercontent.com/2564187/77227903-3e1e7b80-6b8c-11ea-863a-1f541e93d51b.png)

# Workaround

If the requests is sent through [`https://cors-anywhere.herokuapp.com/`](https://cors-anywhere.herokuapp.com/), everything works as expected (at least in the case of this `GET` request, had some issues with a PUT request with data using that approach). Check out `main.js` to send the request through this service.

Will be happy to provide more info as needed.

**Comment by skorokithakis** [comment]
This should now be fixed. Please let me know if you're still having problems with it.

**Comment by Nagasaki45** [comment]
Amazing @skorokithakis! The CORS headers are now in place. Thanks a lot!!!

I've just noticed the same issue with accessing the user personal URL. For example [https://www.eternum.io/user/nagasaki45/](https://www.eternum.io/user/nagasaki45/). Getting this through a CORS proxy is not an issue, as there's no authentication involved. Would you consider adding CORS headers for this as well?

**Comment by skorokithakis** [comment]
Err, sure, but why do you need to get the redirect via JS?

**Comment by Nagasaki45** [comment]
The idea is that users will keep RSS feeds on IPFS and available on eternum on their chosen URL. The the front-end app I'm working on should be able to fetch the feed, edit, and update it.
Anyway, adding CORS headers in that case is not an absolute necessity. As you said, that's not a very common use case. I just thought I'd flag this out. Will be happy with whatever decision you make.
Thanks again for the help and super quick responses!

**Comment by skorokithakis** [comment]
I'm wondering whether it'd be more useful to add the current IPFS CID that the user's URL points to to the API, instead of hacking around it by fetching the redirect target.

**Comment by Nagasaki45** [comment]
That makes a lot of sense! And it's already part of the API. Will fetch the hash and request the content through the gateway instead of trying to get it from the user URL directly. Thanks a lot for the help! Think I'll close the issue now.
